### ISSUE TITLE
Add usage of pycurses with keyboard keys (arrows) and enter

### ISSUE THREAD

**Issue by jakubbogucki** [jakubbogucki/flyt#1]
Like in title. Highlitght actually chosen link and enter to copy videos url to clipboard.

**Comment by jonasfs** [comment]
Hi! I just gave this a go, I'll submit a PR shortly.

I had to change quite a bit of the code to make it work with pycurses, and there are a few issues that should be addressed (like needing a minimum window height, test coverage). It is fully functional on default settings though. I also cant test it on Windows right now, I hope thats not a problem.

**Comment by jakubbogucki** [comment]
Not a problem, I'm not using Windows. I left review.
